### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by drnic** [perplexes/m2r#1]
I am feeling a bit stupid. I have mongrel2 installed via homebrew; and when I spin up any of the examples, such as:

<pre>
rvm jruby
rackup example/lobster.ru
</pre>

The terminal hangs, can only be killed via `kill -9`, and pointing the browser at `http://localhost:6767/handlertest` says the browser cannot connect.

So I must be doing something dumb or am misunderstanding what I'm supposed to do next. Sorry about that.

How do I get any of the examples to work? Thanks for any help.

As an aside, I installed all the test dependencies, only to discover the "hey buddy, you should probably rename this file and start testing for real" error :/

**Comment by perplexes** [comment]
Howdy.

I suppose I should start by saying that this is an experiment in motion, and mongrel2 is still a moving target, and I don't know anyone who's running it in production besides Zed.

I apologize for the confusion and non-worky-ness. I'll take a look tonight.

**Comment by perplexes** [comment]
Hokay, I got it running with a little modification, which I just pushed (on GH and RubyGems.org). I couldn't reproduce the hanging issue, but I also couldn't ^C my way out of it (and it started up WEBrick?), so I'll be working on that. Plus there's some testing & refactoring to do!

In the mean time, here are my gems that worked for me:

bouncy-castle-java (1.5.0145.2)
columnize (0.3.1)
ffi (0.6.3)
ffi-rzmq (0.6.0)
gemcutter (0.6.1)
git (1.2.5)
jeweler (1.4.0)
jruby-openssl (0.7.1)
json (1.4.6)
json_pure (1.4.6)
rack (1.2.1)
rake (0.8.7)
rdoc (2.5.11)
rspec (1.3.0)
ruby-debug (0.10.3)
ruby-debug-base (0.10.3.2)
rubyforge (2.0.4)
sources (0.0.1)

This includes adding the gems that come with JRuby to the GEM_PATH through

```
export GEM_PATH=$GEM_PATH:/Users/colin/.rvm/rubies/jruby 1.5.2/lib/ruby/gems/1.8
```

because, you know, RVM doesn't add them, which I'll file a ticket for.

Could you let me know what gems you're running?

**Comment by paneq** [comment]
Can we close? No update in 2 years.
